config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get '/sign_up', to: 'devise/registrations#new', as: :sign_up
    get '/sign_in', to: 'devise/sessions#new', as: :sign_in
  end

  root 'static_pages#home', as: :home
  resources :users, :only => [:show, :index]
  resources :posts do
    resources :comments
  end
  

  get 'static_pages/faq', as: :faq
  get 'static_pages/general_info', as: :general_info
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user.name
    @comment.save
    redirect_to post_path(@post)
  end
 
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:title, :author, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
	def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user.name
    if @post.save
    	redirect_to @post
  	else
    	render 'new'
  	end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

    def update 
    @post = Post.find(params[:id])
    @post.author = current_user.name
      if @post.update(post_params)
        redirect_to @post
      else
        render 'edit'
      end
  end

	def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path


	end 

  

  private
  def post_params
    params.require(:post).permit(:title, :author, :body)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # One feature of rails is that it only allows white listed parameters to be accessed
  # Since the default devise controllers are in the gem, we can't add extra fields to the database unless we change the registrations controller.
  # Up top, you can see that we're inheriting from the Devise::RegistrationsController.
  # This means that all of our default Devise stuff works, and we can add some extras
  # In this case, I added the attributes name and bio to the model and changed the sign_up and account_update params to reflect that.
  private

  def sign_up_params
    params.require(:user).permit(:name, :bio, :unit, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :bio, :unit, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def FAQ
  end

  def Home
  end

  def General_Info
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<p>
  <strong>Author:</strong>
  <%= comment.author %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
index.html.erb

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/_notices.html.erb
<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Community</title>
  <meta name="viewport" content="width=device-width">
  <meta charset="utf-8">
  <%= favicon_link_tag(source='condofavicon.ico') %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700|Roboto:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="container">
<nav>
<ul>
	<li>
		<%= link_to 'Home', home_path %>

	</li>
	<li>
		<%= link_to 'FAQ', faq_path %>
	</li>
	<li>
		<%= link_to 'General Info', general_info_path %>
	</li>
<li>
<%= link_to 'Users', users_path %> 
</li>
<li>
<%= link_to 'Posts', posts_path %>
</li>
<li>
<%= link_to 'Login', sign_in_path %>
</li>
<li>
<%= link_to 'Sign Up', sign_up_path %>
</li>
<li>
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
</li>
</ul>
</nav>
<%= render 'layouts/notices' %>

<%= yield %>

</div>
</body>
</html>

app/views/notification/comment_notifier.html.erb
<h1>Notification#comment_notifier</h1>

<p>
  <%= @greeting %>, find me in app/views/notification/comment_notifier.html.erb
</p>

app/views/notification/comment_notifier.text.erb
Notification#comment_notifier

<%= @greeting %>, find me in app/views/notification/comment_notifier.text.erb

app/views/notification/post_notifier.html.erb
<h1>Notification#post_notifier</h1>

<p>
  <%= @greeting %>, find me in app/views/notification/post_notifier.html.erb
</p>

app/views/notification/post_notifier.text.erb
Notification#post_notifier

<%= @greeting %>, find me in app/views/notification/post_notifier.text.erb

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', post_path %>

app/views/posts/index.html.erb
<h1>Listing of all posts</h1>

<%= link_to 'New Posts', new_post_path %>
 
<% @posts.each do |post| %>
<p>
<%= link_to post.title, post_path(post) %><br>
Posted by: <%= post.author %>
<hr>
</p>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>


<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
 
<h2>Comments</h2>
<% @post.comments.each do |comment| %>

	<p>
		<strong>Author:</strong> <%= comment.author %>
		<strong>Comment:</strong> <%= comment.body %>
	</p>

<% end %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>

  <%= link_to 'Back', posts_path %>
  <%= link_to 'Edit', edit_post_path(@post) %>

app/views/static_pages/FAQ.html.erb
<h1>StaticPages#FAQ</h1>
<p>Find me in app/views/static_pages/FAQ.html.erb</p>

app/views/static_pages/General_Info.html.erb
<h1>StaticPages#General_Info</h1>
<p>Find me in app/views/static_pages/General_Info.html.erb</p>

app/views/static_pages/Home.html.erb
<h1>StaticPages#Home</h1>
<p>Find me in app/views/static_pages/Home.html.erb</p>

app/views/static_pages/faq.html.erb
<h1>Frequently Asked Questions</h1>

<p class="intro">Welcome to our FAQ page, here you'll find some common questions with awesome answers</p>

<ul class="faqul">

<li><strong>Q:</strong>What our the gym hours?</li>
<p><strong><em>A:</em></strong>Our lovely gym is open from 5AM to 1AM 7 days a week for your fitness needs! #gottakeepittight</p>

<li><strong>Q:</strong>Where do guests park?</li>
<p><strong><em>A:</em></strong>Your guests will be able to find convient parking on the west side of the building next to the giant beaker sign in the covered carports.</p>

<li><strong>Q:</strong>Shoot, I LOST my keys, WHAT do I do?</li>
<p><strong><em>A:</em></strong>No worries, loosing your keys happens, contact the security team at <a href="tel:420-303-1988">(420) 303-1988</a><br>OR, if you don't got your phone, visit the secuirty booth in main parking area -they'll help you out!</p>

<li><strong>Q:</strong>I lost my parking pass, where can I get a new one?</li>
<p><strong><em>A:</em></strong>Send out an email to our parking team at: <a href="mailto:devpointcondoparking@devcondo.com">DevCondoParkTeam</a><br>You'll here back from the team within 24hrs; in the meantime: notify main parking security booth and park in guest parking.
</p>

<li><strong>Q:</strong>There's an issue with the onsite laundry, who do I contact?</li>
<p><strong><em>A:</em></strong>We want you to be able to do laundry 24/7, to expedite the response contact laundry-response-team directly at: <a href="tel:024-303-8891">(024) 303-8891</a><br>Response time is usually 2-3hrs, so you'll be <em>so fresh and so clean, super quick</em></p>

</ul>

<div class="timenow">
<span>The date/time now is: <%= Time.now.in_time_zone("Mountain Time (US & Canada)") %></span>
</div>

app/views/static_pages/general_info.html.erb
<h1>General Information</h1>
<p class="intro">Welcome to the general info section</p>

<hX>The condo's ammenitites:</hX>
<ul class="geninfoul">
    <li>Free Sunday Brunch</li>
    <li>Free access to our state of the art gym, swimming pool, sauna, steam room, yoga studio, dance stage, and 'party' style hot tub.</li>
    <li>Complementary bi-weekly cleaning service</li>
    <li>Covered parking</li>
    <li>Free use of washer and dryer facilities</li>
    <li>Free cable/internet access via Google Fiber services!</li>
</ul>

<hX>Contacts:</hX>
<ul class="geninfoul">
    <li>General Managment: <a href="tel:329-123-8293">(329) 123-8293</a></li>
    <li>Leasing Office: <a href="tel:381-321-8321">(381) 321-8321</a></li>
    <li>Laundry Response Team: <a href="tel:024-303-8891">(024) 303-8891</a></li>
    <li>Security Team: <a href="tel:420-303-1988">(420) 303-1988</a></li>
    <li>Gym Crew: <a href="tel:672-134-0218">(672) 134-0218</a></li>
    <li>Internet/TV Response Team: <a href="tel:324-112-9732">(324) 112-9732</a></li>
</ul>

<div class="timenow">
<span>The date/time now is: <%= Time.now.in_time_zone("Mountain Time (US & Canada)") %></span>
</div>

app/views/static_pages/home.html.erb
<h1>DevPoint Community | Welcome Home!</h1>
<p class="intro">Welcome to OUR condo!  WE LOVE HAVING YOU HERE! Be sure to sign up or sign in to access the posts section! 

<div><%= image_tag "Picture1.jpg", class:"pics" %></div>

</p>

<hX>The condo's history:</hX>
<ul class="homeinfoul">
    <li>Established in 1980 once A Flock Of Seagals left town.</li>
    <li>Remodeled in 1999 in prep for Y2K; also made sure to clean up the massive party that was thrown...because the whole condo DID indeed party like it was 1999.</li>
    <li>Recieved reduced admission to the bowling alley below the condo once the teenage mutant ninja turtles decided to head back down to the sewers in 2004.</li>
</ul>

<div class="timenow">
<span>The date/time now is: <%= Time.now.in_time_zone("Mountain Time (US & Canada)") %></span>
</div>


<% if current_user %>
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> | 
<%= link_to 'Users', users_path %> | 
<%= link_to 'Posts', posts_path %>
<% else %>
<%= link_to 'Login', sign_in_path, class: 'auth_links' %>
<%= link_to 'Sign Up', sign_up_path, class: 'auth_links' %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>DevPoint Community Users</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.unit %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
        <td><%= link_to 'Delete', edit_user_registration_path, method: :delete, 
                                         data: { 
                                         confirm: 'Are you sure you want to delete this user?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>